---
name: CPANPLUS-Dist-Mdv
version: 0.1.0
author:
  - 'Jerome Quelin <jquelin@cpan.org>'
abstract: a cpanplus backend to build mandriva rpms
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  CPANPLUS: 0
build_requires:
  CPANPLUS: 0
  Test::More: 0
  perl: 5.008
provides:
  CPANPLUS::Dist::Mdv:
    file: lib/CPANPLUS/Dist/Mdv.pm
    version: 0.1.0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
